### ISSUE TITLE
Check that all FIDs and IID in .phe and .fam table match

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/gcaer#7]
The error by GenoCAE is not too obvious (see https://github.com/AJResearchGroup/richel/issues/108 for details)

```
Traceback (most recent call last):
  File "/home/richel/GitHubs/GenoCAE/run_gcae.py", line 1619, in <module>
    main()
  File "/home/richel/GitHubs/GenoCAE/run_gcae.py", line 970, in main
    phenotargets_init = generatepheno(phenodata, poplist)
  File "/home/richel/GitHubs/GenoCAE/run_gcae.py", line 621, in generatepheno
    return tf.expand_dims(tf.convert_to_tensor([data.get((fam, name), None) for name, fam in poplist]), axis=-1)
  File "/home/richel/.local/share/ormr_gcaer/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1283, in convert_to_tensor_v2
    as_ref=False)
  File "/home/richel/.local/share/ormr_gcaer/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1341, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/richel/.local/share/ormr_gcaer/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 321, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/richel/.local/share/ormr_gcaer/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 262, in constant
    allow_broadcast=True)
  File "/home/richel/.local/share/ormr_gcaer/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/richel/.local/share/ormr_gcaer/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
```

**Comment by richelbilderbeek** [comment]
Cannot break `check_gcae_input_files` anymore. Done!
