### ISSUE TITLE
Fix gcae_project

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/gcaer#9]
Here is the last output from `test-workflow.R`:

```
(base) richel@N141CU:~$ '/home/richel/.local/share/ormr_gcaer/bin/python3.6' ~/.local/share/GenoCAE/run_gcae.py project --datadir /home/richel/GitHubs/gcaer/inst/extdata/ --data gcae_input_files_1 --model_id M1 --train_opts_id ex3 --data_opts_id b_0_4 --superpops /home/richel/GitHubs/gcaer/inst/extdata/gcae_input_files_1_labels.csv --trainedmodeldir /home/richel/.cache/gcaer/file2c72e5bf5bb9e --pheno_model_id=p2
2022-01-31 16:15:37.423008: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2022-01-31 16:15:37.445777: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2099940000 Hz
2022-01-31 16:15:37.446241: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55749f0cff60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-01-31 16:15:37.446259: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-01-31 16:15:37.446346: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
tensorflow version 2.2.0

______________________________ arguments ______________________________
train : False
datadir : /home/richel/GitHubs/gcaer/inst/extdata/
data : gcae_input_files_1
model_id : M1
train_opts_id : ex3
data_opts_id : b_0_4
save_interval : None
epochs : None
resume_from : None
trainedmodeldir : /home/richel/.cache/gcaer/file2c72e5bf5bb9e
pheno_model_id : p2
project : True
superpops : /home/richel/GitHubs/gcaer/inst/extdata/gcae_input_files_1_labels.csv
epoch : None
pdata : None
trainedmodelname : None
plot : False
animate : False
evaluate : False
metrics : None

______________________________ data opts ______________________________
sparsifies : [0.0, 0.1, 0.2, 0.3, 0.4]
norm_opts : {'flip': False, 'missing_val': -1.0}
norm_mode : genotypewise01
impute_missing : True
validation_split : 0.2

______________________________ train opts ______________________________
learning_rate : 0.00032
batch_size : 10
noise_std : 0.0032
n_samples : -1
loss : {'module': 'tf.keras.losses', 'class': 'CategoricalCrossentropy', 'args': {'from_logits': False}}
regularizer : {'reg_factor': 1e-07, 'module': 'tf.keras.regularizers', 'class': 'l2'}
lr_scheme : {'module': 'tf.keras.optimizers.schedules', 'class': 'ExponentialDecay', 'args': {'decay_rate': 0.96, 'decay_steps': 100, 'staircase': False}}
______________________________
Imputing originally missing genotypes to most common value.
Reading ind pop list from /home/richel/GitHubs/gcaer/inst/extdata/gcae_input_files_1.fam
Reading ind pop list from /home/richel/GitHubs/gcaer/inst/extdata/gcae_input_files_1.fam
Mapping files: 100%|█████████████████████████████| 3/3 [00:00<00:00, 241.90it/s]
Projecting epochs: [1]
Already projected: []
In DG.get_train_set: number of -1.0 genotypes in train: 0
In DG.get_train_set: number of -9 genotypes in train: 0
In DG.get_train_set: number of 0 values in train mask: 0
Could not write to file /home/richel/.cache/gcaer/file2c72e5bf5bb9eae.M1.ex3.b_0_4.gcae_input_files_1.p2/gcae_input_files_1/encoded_data.h5.

______________________________ Building model ______________________________
Adding layer: Conv1D: {'filters': 8, 'kernel_size': 5, 'padding': 'same', 'strides': 1}
Adding layer: BatchNormalization: {}
Adding layer: ResidualBlock2: {'filters': 8, 'kernel_size': 5}
--- conv1d  filters: 8 kernel_size: 5
--- batch normalization
--- conv1d  filters: 8 kernel_size: 5
--- batch normalization
Adding layer: MaxPooling1D: {'pool_size': 5, 'strides': 2, 'padding': 'same'}
Adding layer: Conv1D: {'filters': 8, 'kernel_size': 5, 'padding': 'same', 'activation': 'elu'}
Adding layer: BatchNormalization: {}
Adding layer: Flatten: {}
Adding layer: Dropout: {'rate': 0.01}
Adding layer: Dense: {'units': 75}
Adding layer: Dropout: {'rate': 0.01}
Adding layer: Dense: {'units': 75, 'activation': 'elu'}
Adding layer: Dense: {'units': 2, 'name': 'encoded'}
Adding layer: Dense: {'units': 75, 'activation': 'elu'}
Adding layer: Dropout: {'rate': 0.01}
Adding layer: Dense: {'units': 75, 'activation': 'elu'}
Adding layer: Dropout: {'rate': 0.01}
Adding layer: Dense: {'units': 8}
Adding layer: Reshape: {'target_shape': (1, 8), 'name': 'i_msvar'}
Adding layer: Conv1D: {'filters': 8, 'kernel_size': 5, 'padding': 'same', 'activation': 'elu'}
Adding layer: BatchNormalization: {}
Adding layer: Reshape: {'target_shape': (1, 1, 8)}
Adding layer: UpSampling2D: {'size': (2, 1)}
Adding layer: Reshape: {'target_shape': (2, 8)}
Adding layer: ResidualBlock2: {'filters': 8, 'kernel_size': 5}
--- conv1d  filters: 8 kernel_size: 5
--- batch normalization
--- conv1d  filters: 8 kernel_size: 5
--- batch normalization
Adding layer: Conv1D: {'filters': 8, 'kernel_size': 5, 'padding': 'same', 'activation': 'elu', 'name': 'nms'}
Adding layer: BatchNormalization: {}
Adding layer: Conv1D: {'filters': 1, 'kernel_size': 1, 'padding': 'same'}
Adding layer: Flatten: {'name': 'logits'}

______________________________ Building model ______________________________
Adding layer: Dense: {'units': 8}
Adding layer: LeakyReLU: {}
Adding layer: Dense: {'units': 1}
No marker specific variable.
########################### epoch 1 ###########################
Reading weights from /home/richel/.cache/gcaer/file2c72e5bf5bb9eae.M1.ex3.b_0_4.gcae_input_files_1.p2/weights/1
tf.Tensor(
[0.12228771 0.13889855 0.1153423  0.12228771 0.12228771 0.1153423
 0.1153423  0.1153423  0.13889855 0.13889855 0.13889855 0.12228771
 0.1153423  0.12228771 0.13889855 0.13889855 0.13889855 0.12228771
 0.13889855 0.13889855 0.13889855 0.1153423  0.1153423  0.13889855
 0.12228771 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.13889855 0.12228771 0.12228771 0.13889855 0.13889855
 0.13889855 0.12228771 0.1153423  0.13889855 0.13889855 0.13889855
 0.12228771 0.13889855 0.13889855 0.12228771 0.13889855 0.12228771
 0.13889855 0.1153423  0.12228771 0.12228771 0.13889855 0.13889855
 0.13889855 0.1153423  0.13889855 0.1153423  0.12228771 0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.13889855 0.12228771 0.12228771 0.13889855 0.13889855
 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855 0.1153423
 0.1153423  0.13889855 0.12228771 0.1153423  0.12228771 0.12228771
 0.13889855 0.13889855 0.1153423  0.13889855 0.12228771 0.12228771
 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855 0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.13889855 0.1153423  0.12228771 0.12228771 0.1153423
 0.12228771 0.12228771 0.12228771 0.1153423  0.13889855 0.13889855
 0.13889855 0.13889855 0.12228771 0.13889855 0.13889855 0.1153423
 0.13889855 0.13889855 0.12228771 0.13889855 0.13889855 0.12228771
 0.13889855 0.13889855 0.1153423  0.12228771 0.13889855 0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.13889855 0.1153423  0.1153423  0.13889855 0.13889855
 0.12228771 0.13889855 0.13889855 0.12228771 0.12228771 0.1153423
 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855
 0.1153423  0.13889855 0.13889855 0.13889855 0.12228771 0.12228771
 0.12228771 0.13889855 0.12228771 0.13889855 0.13889855 0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.1153423  0.1153423  0.13889855 0.1153423  0.13889855 0.13889855
 0.1153423  0.13889855 0.13889855 0.1153423  0.1153423  0.12228771
 0.1153423  0.1153423  0.13889855 0.12228771 0.13889855 0.1153423
 0.13889855 0.13889855 0.13889855 0.12228771 0.12228771 0.13889855
 0.1153423  0.13889855 0.12228771 0.13889855 0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.13889855 0.13889855 0.13889855 0.12228771 0.13889855
 0.1153423  0.1153423  0.12228771 0.1153423  0.1153423  0.1153423
 0.13889855 0.12228771 0.13889855 0.13889855 0.1153423  0.13889855
 0.13889855 0.1153423  0.13889855 0.13889855 0.12228771 0.12228771
 0.12228771 0.13889855 0.12228771 0.13889855 0.13889855 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.13889855 0.1153423  0.13889855 0.12228771
 0.13889855 0.13889855 0.13889855 0.1153423  0.13889855 0.12228771
 0.12228771 0.13889855 0.13889855 0.1153423  0.1153423  0.12228771
 0.1153423  0.12228771 0.1153423  0.13889855 0.13889855 0.13889855
 0.12228771 0.13889855 0.1153423  0.13889855 0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.1153423  0.12228771 0.12228771 0.13889855 0.1153423
 0.13889855 0.13889855 0.1153423  0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.12228771 0.12228771 0.13889855 0.13889855
 0.13889855 0.1153423  0.13889855 0.12228771 0.1153423  0.12228771
 0.13889855 0.1153423  0.12228771 0.13889855 0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.13889855 0.13889855 0.12228771 0.13889855 0.1153423
 0.13889855 0.1153423  0.12228771 0.13889855 0.13889855 0.12228771
 0.1153423  0.13889855 0.12228771 0.13889855 0.13889855 0.13889855
 0.13889855 0.12228771 0.13889855 0.1153423  0.1153423  0.13889855
 0.1153423  0.12228771 0.13889855 0.1153423  0.13889855 0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.1153423  0.1153423  0.12228771 0.12228771 0.12228771
 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855 0.12228771
 0.12228771 0.13889855 0.13889855 0.13889855 0.12228771 0.12228771
 0.12228771 0.12228771 0.13889855 0.1153423  0.13889855 0.13889855
 0.12228771 0.13889855 0.12228771 0.12228771 0.13889855 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.13889855 0.13889855 0.1153423  0.13889855 0.1153423
 0.13889855 0.1153423  0.1153423  0.13889855 0.13889855 0.13889855
 0.1153423  0.12228771 0.13889855 0.13889855 0.12228771 0.13889855
 0.13889855 0.1153423  0.1153423  0.13889855 0.13889855 0.12228771
 0.13889855 0.13889855 0.1153423  0.12228771 0.13889855 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.13889855 0.12228771 0.13889855 0.13889855
 0.13889855 0.1153423  0.13889855 0.13889855 0.13889855 0.12228771
 0.13889855 0.13889855 0.13889855 0.1153423  0.12228771 0.12228771
 0.13889855 0.13889855 0.13889855 0.12228771 0.13889855 0.12228771
 0.13889855 0.13889855 0.12228771 0.12228771 0.12228771 0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.12228771 0.13889855 0.12228771 0.1153423  0.13889855
 0.13889855 0.12228771 0.12228771 0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.13889855 0.13889855 0.12228771 0.1153423
 0.12228771 0.13889855 0.12228771 0.13889855 0.13889855 0.12228771
 0.12228771 0.12228771 0.12228771 0.13889855 0.12228771 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.1153423  0.13889855 0.13889855 0.12228771 0.13889855 0.1153423
 0.1153423  0.13889855 0.1153423  0.12228771 0.13889855 0.1153423
 0.12228771 0.13889855 0.13889855 0.13889855 0.13889855 0.12228771
 0.12228771 0.12228771 0.13889855 0.1153423  0.1153423  0.1153423
 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855 0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.1153423  0.12228771 0.1153423  0.13889855 0.13889855 0.1153423
 0.13889855 0.1153423  0.13889855 0.12228771 0.13889855 0.1153423
 0.12228771 0.13889855 0.1153423  0.13889855 0.1153423  0.13889855
 0.1153423  0.13889855 0.12228771 0.13889855 0.1153423  0.13889855
 0.1153423  0.1153423  0.13889855 0.1153423  0.13889855 0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.13889855 0.1153423  0.12228771 0.13889855 0.13889855
 0.13889855 0.1153423  0.13889855 0.1153423  0.13889855 0.1153423
 0.1153423  0.1153423  0.12228771 0.13889855 0.1153423  0.1153423
 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855 0.12228771
 0.12228771 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.1153423  0.12228771 0.1153423  0.13889855 0.13889855 0.13889855
 0.12228771 0.1153423  0.12228771 0.12228771 0.13889855 0.1153423
 0.13889855 0.13889855 0.13889855 0.1153423  0.13889855 0.13889855
 0.13889855 0.1153423  0.1153423  0.13889855 0.13889855 0.13889855
 0.13889855 0.1153423  0.12228771 0.12228771 0.12228771 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.13889855 0.1153423  0.1153423  0.1153423  0.13889855
 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855 0.1153423
 0.12228771 0.13889855 0.1153423  0.12228771 0.13889855 0.12228771
 0.1153423  0.13889855 0.12228771 0.12228771 0.12228771 0.12228771
 0.13889855 0.12228771 0.13889855 0.13889855 0.12228771 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.13889855 0.1153423  0.13889855 0.13889855 0.13889855
 0.12228771 0.12228771 0.13889855 0.1153423  0.13889855 0.13889855
 0.13889855 0.1153423  0.13889855 0.13889855 0.1153423  0.13889855
 0.12228771 0.13889855 0.13889855 0.1153423  0.13889855 0.13889855
 0.13889855 0.13889855 0.1153423  0.12228771 0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.12228771 0.12228771 0.13889855 0.1153423  0.12228771
 0.13889855 0.13889855 0.13889855 0.1153423  0.1153423  0.1153423
 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855 0.1153423
 0.13889855 0.13889855 0.1153423  0.13889855 0.12228771 0.12228771
 0.13889855 0.13889855 0.13889855 0.13889855 0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.13889855 0.12228771 0.1153423  0.13889855
 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.13889855 0.13889855 0.12228771 0.12228771
 0.13889855 0.12228771 0.13889855 0.12228771 0.13889855 0.12228771
 0.1153423  0.12228771 0.1153423  0.13889855 0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.12228771 0.1153423  0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.13889855 0.12228771 0.1153423  0.1153423
 0.12228771 0.1153423  0.1153423  0.13889855 0.1153423  0.1153423
 0.12228771 0.1153423  0.12228771 0.12228771 0.13889855 0.13889855
 0.1153423  0.13889855 0.13889855 0.12228771 0.13889855 0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.1153423  0.1153423  0.13889855 0.12228771 0.1153423
 0.13889855 0.12228771 0.13889855 0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.13889855 0.12228771 0.13889855 0.13889855
 0.13889855 0.13889855 0.13889855 0.13889855 0.1153423  0.12228771
 0.13889855 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.1153423  0.1153423  0.13889855 0.1153423
 0.13889855 0.13889855 0.13889855 0.1153423  0.12228771 0.13889855
 0.1153423  0.12228771 0.13889855 0.1153423  0.13889855 0.1153423
 0.13889855 0.1153423  0.12228771 0.13889855 0.1153423  0.12228771
 0.12228771 0.13889855 0.13889855 0.1153423  0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.1153423  0.13889855 0.13889855 0.1153423  0.1153423
 0.1153423  0.12228771 0.13889855 0.13889855 0.13889855 0.12228771
 0.12228771 0.1153423  0.13889855 0.12228771 0.13889855 0.13889855
 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.12228771 0.12228771 0.13889855 0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.12228771 0.12228771 0.1153423  0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.13889855 0.1153423  0.1153423  0.13889855
 0.13889855 0.12228771 0.12228771 0.12228771 0.13889855 0.1153423
 0.13889855 0.12228771 0.13889855 0.13889855 0.1153423  0.1153423
 0.12228771 0.1153423  0.1153423  0.13889855 0.1153423  0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.12228771 0.13889855 0.12228771 0.13889855 0.1153423
 0.12228771 0.1153423  0.13889855 0.13889855 0.12228771 0.1153423
 0.1153423  0.13889855 0.13889855 0.1153423  0.1153423  0.1153423
 0.1153423  0.13889855 0.13889855 0.12228771 0.12228771 0.12228771
 0.13889855 0.13889855 0.13889855 0.12228771 0.13889855 0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.12228771 0.13889855 0.12228771 0.13889855
 0.1153423  0.12228771 0.12228771 0.1153423  0.12228771 0.13889855
 0.13889855 0.12228771 0.1153423  0.12228771 0.12228771 0.13889855
 0.13889855 0.13889855 0.1153423  0.12228771 0.1153423  0.1153423
 0.1153423  0.12228771 0.13889855 0.1153423  0.1153423  0.13889855], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.12228771 0.13889855 0.13889855 0.1153423  0.13889855
 0.13889855 0.1153423  0.1153423  0.12228771 0.13889855 0.13889855
 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855 0.13889855
 0.13889855 0.12228771 0.1153423  0.12228771 0.13889855 0.12228771
 0.12228771 0.13889855 0.12228771 0.1153423  0.1153423  0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.12228771 0.13889855 0.12228771 0.13889855
 0.13889855 0.13889855 0.12228771 0.1153423  0.13889855 0.1153423
 0.1153423  0.1153423  0.13889855 0.12228771 0.1153423  0.13889855
 0.13889855 0.1153423  0.13889855 0.1153423  0.13889855 0.12228771], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.13889855 0.13889855 0.12228771 0.1153423
 0.13889855 0.12228771 0.1153423  0.13889855 0.13889855 0.13889855
 0.13889855 0.12228771 0.12228771 0.12228771 0.13889855 0.13889855
 0.12228771 0.12228771 0.12228771 0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.12228771 0.12228771 0.1153423  0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.1153423  0.1153423  0.13889855 0.1153423  0.12228771
 0.13889855 0.13889855 0.1153423  0.13889855 0.1153423  0.12228771
 0.13889855 0.1153423  0.1153423  0.1153423  0.13889855 0.13889855
 0.1153423  0.13889855 0.13889855 0.13889855 0.13889855 0.13889855
 0.13889855 0.13889855 0.1153423  0.13889855 0.13889855 0.1153423 ], shape=(30,), dtype=float32)
(30,)
tf.Tensor(
[0.13889855 0.12228771 0.13889855 0.13889855 0.12228771 0.12228771
 0.13889855 0.12228771 0.1153423  0.13889855], shape=(10,), dtype=float32)
(10,)
array([[0.45931378],
       [0.341766  ],
       [0.18559882],
       [0.45931378],
       [0.45931378]], dtype=float32)
[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]] array([[1. ],
       [0.5],
       [0. ],
       [1. ],
       [1. ]])
Traceback (most recent call last):
  File "/home/richel/.local/share/GenoCAE/run_gcae.py", line 1619, in <module>
    main()
  File "/home/richel/.local/share/GenoCAE/run_gcae.py", line 1368, in main
    plot_coords_by_superpop(coords_by_pop,"{0}/dimred_e_{1}_by_superpop".format(results_directory, epoch), superpopulations_file, plot_legend = epoch == epochs[0])
  File "/home/richel/.local/share/GenoCAE/utils/visualization.py", line 222, in plot_coords_by_superpop
    max_num_pops = max([len(superpop_dict[spop]) for spop in superpops])
ValueError: max() arg is an empty sequence
```

**Comment by richelbilderbeek** [comment]
My theory is that there need to be two superpopulations for this to work.

**Comment by richelbilderbeek** [comment]
This theory is rejected: by using two superpopulations, the same error is given.

**Comment by richelbilderbeek** [comment]
Works!
